# Generated by Django 6.0.2 on 2026-02-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cpf',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
