# Generated by Django 6.0.2 on 2026-02-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0002_alter_users_cpf_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cpf',
            field=models.BigIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
