# Generated by Django 6.0.2 on 2026-02-18 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0003_alter_users_cpf_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='cpf',
            field=models.CharField(unique=True),
        ),
    ]
