# Generated by Django 6.0.2 on 2026-03-01 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0005_usertypes_users_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='cpf',
        ),
    ]
