# Generated by Django 6.0.2 on 2026-02-22 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_holidays_alter_schedules_user_phone_court_blocks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holidays',
            old_name='date',
            new_name='dates',
        ),
        migrations.RenameField(
            model_name='holidays',
            old_name='name',
            new_name='description',
        ),
    ]
