# Generated by Django 6.0.2 on 2026-02-22 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_schedules_user_id_nullable'),
        ('booking', '0003_rename_date_holidays_dates_and_more'),
    ]

    operations = [
    ]
