# Generated by Django 6.0.2 on 2026-02-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_merge_20260222_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedules',
            name='user_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='schedules',
            name='user_phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
